name: Build - Test & CodeCoverage
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Eslint CLI
        run: npm install -g @eslint/cli

      - name: Build Angular Project
        run: npm run build

      - name: Run Unit Tests with Jest
        run: npm run test:ci
      
      - name: Run Eslint for sonnar issues
        run: eslint . -f json -o lint/eslint_report.json
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}