name: Deploy Angular to Vercel - Development

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Install Dependencies
        run: npm install

      - name: Build for Development
        run: npm run build:dev

      - name: Alias Development to dev.management-portal-fe..vercel.app
        run: vercel alias set management-portal-fe.vercel.app dev-management-portal-fe.vercel.app --token ${{ secrets.VERCEL_TOKEN }}   
      
      - name: Deploy to Vercel (Preview)
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --org-id=${{ secrets.VERCEL_ORG_ID }} --project-id=${{ secrets.VERCEL_PROJECT_ID }} --yes --env=preview