name: Deploy Angular to Vercel - Development

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Install Dependencies
        run: npm install

      - name: Build for Development
        run: npm run build:dev

      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy ./dist/management-portal-fe --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" dev-management-portal-fe.vercel.app