name: Deploy Angular to Vercel - Development

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Install Dependencies
        run: npm install

      - name: Build for Development
        run: npm run build:dev

      - name: Alias Development to dev.management-portal-fe..vercel.app
        run: vercel alias set management-portal-fe.vercel.app dev-management-portal-fe.vercel.app --token ${{ secrets.VERCEL_TOKEN }}   

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --target=development --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}